version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Package Artifact"
      #- echo Code Scanning using SonarQube
      #- mvn verify sonar:sonar
      #- echo Publish Artifact To JFROG  
  build:
    commands:
      - echo Build started on `date`
      - pwd
      - ls -lrta
      - ls -lrt $CODEBUILD_SRC_DIR/settings.xml
      - cp -pvr $CODEBUILD_SRC_DIR/settings.xml ~/.m2/settings.xml
      - mvn deploy
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/b78am.war
